### ISSUE TITLE
How does hrefTargetBlank work?

### ISSUE THREAD

**Issue by kennethlimcp** [ribice/kiss#100]
I have the following setup but the link does not end up opening a new window:

`post.md`:

```
[Telegram bots](https://telegram.org/)
```

`config.toml`

```
[blackfriday]
hrefTargetBlank = true
```

**Comment by mogimogitomato** [comment]
@kennethlimcp 
It's maybe because of hugo's new goldmark markdown renderer.
( `config.toml` 's [blackfriday] sample were getting old. )
Please check hugo's version, also this articles maybe helpful.

https://agrimprasad.com/post/hugo-goldmark-markdown/

**Comment by kennethlimcp** [comment]
@mogimogitomato thanks for the tip! super helpful and i managed to get it working already :)
