### ISSUE TITLE
Recommend submodule instead of normal git clone

### ISSUE THREAD

**Issue by DanielRuf** [ribice/kiss#101]
The following is generally better (do a `git init`in the root folder before doing this step):
`git submodule add git@github.com:ribice/kiss.git themes/kiss`

**Comment by ribice** [comment]
Hi @DanielRuf

If you'd like I can give you maintainer status to maintain `kiss` and fix issues it has. Please let me know. Thanks!

**Comment by DanielRuf** [comment]
If I find the time I can provide the needed patches / changes.

**Comment by DanielRuf** [comment]
If I find the time I can provide the needed patches / changes.
Currently I am rewriting so much to get it like my current Gatsby based blog on https://blog.daniel-ruf.de so there is probably more I stumple upon.
