### ISSUE TITLE
Do not use target="_blank" for social media links

### ISSUE THREAD

**Issue by DanielRuf** [ribice/kiss#103]
`target="_blank"` is bad for the accessibility and for the security, you also forgot to add `noreferrer` to the `rel` attribute.

See also https://blog.daniel-ruf.de/target-blank-considered-harmful/.

**Comment by DanielRuf** [comment]
What is the preferred solution? Remove the `target` attribute or set the `rel` attribute to mitigate tab nabbing attacks?

**Comment by ribice** [comment]
I have no idea to be honest. Most of my work is backend/devops and I rarely touch HTML besides some basics. Feel free to implement whatever you consider better.
