### ISSUE TITLE
link and meta tags are not self-closing

### ISSUE THREAD

**Issue by DanielRuf** [ribice/kiss#109]
Something else that I found: https://github.com/ribice/kiss/blob/master/layouts/partials/header.html#L5

link and meta are void elements and not self-closing.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#Examples and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#Examples

I will try to provide a PR in a few days when I find the time.

**Comment by ribice** [comment]
Any update on this @DanielRuf ?

**Comment by DanielRuf** [comment]
Unfortunately I had not much time so far and currently work related projects are need my whole time.
I will try to find some time this or next weekend.

**Comment by DanielRuf** [comment]
Thanks for the reminder.

Unfortunately I had not much time so far and currently work related projects are need my whole time.
I will try to find some time this or next weekend.
