### ISSUE TITLE
CSS framework ?

### ISSUE THREAD

**Issue by Plorenzo** [ribice/kiss#15]
I would like to make some changes to the structure of the site, but is kind of difficult to guess what are the css classes doing without any documentation. 

Are you using any css framework in particular?

**Comment by ribice** [comment]
Hey,

The original author did use a framework - Bulma. You can check it on his repo ([LINK](https://github.com/tanksuzuki/hemingway)).

I've made just some small changes, so you can easily move them from plain css to Bulma.

**Comment by Plorenzo** [comment]
Awesome, thanks. Bulma is what I was looking for
