### ISSUE TITLE
Strange look of Cyrillic (Russian) font

### ISSUE THREAD

**Issue by paskal** [ribice/kiss#20]
Hello!

$subj, when I'm building my [blog](https://github.com/paskal/terrty/tree/master/blog) source for Cyrillic font I see the picture which drastically different from the Latin characters render:
![image](https://user-images.githubusercontent.com/712534/37682762-7893649c-2c9b-11e8-8753-74e75f2bf054.png)

Also preview missing HTML formatting (like line breaks), that's what could be seen on screenshot.

**Comment by ribice** [comment]
What font are you using? How did you set it up?

How does it work with other themes?

**Comment by paskal** [comment]
That's standard font of this theme, I guess it just missed Cyrillic.
Similar issue where author just pointed our there is a mechanism for font change which one in need could use: https://github.com/dim0627/hugo_theme_solit/issues/7
If your theme have same customization options, that might be enough.

**Comment by ribice** [comment]
In style css, look for:

textarea {
    font-family: "游ゴシック", YuGothic, "ヒラギノ角ゴ Pro", "Hiragino Kaku Gothic Pro", "メイリオ", Meiryo, sans-serif
}

Add font you like that supports Cyrillic letters (I tried Roboto, works as expected but doesn't look good).
