### ISSUE TITLE
Possible to use categories / sections?

### ISSUE THREAD

**Issue by olehermanse** [ribice/kiss#22]
Hey, I really like your theme, but have one question; Is it possible to add sections / categories in this theme like other hugo themes? (posts, projects, about, et.c.) Either top left next to site name or top right instead of social buttons. (The social buttons could be moved to bottom center for example)

How hard would this be to achieve?

**Comment by ribice** [comment]
I think one of the forks added it. Perhaps you could look there.

I chose this theme for myself because it's minimal, and I preferred not to have those links either. I'd rather not bloat this theme with those links, but it shouldn't be hard to add them.

**Comment by olehermanse** [comment]
Thanks, I found this https://github.com/mateimicu/kiss/commit/ba08009e61d76379ae663eac836f7e959c1808e3#comments .

Modified it to be completely optional. Added PR #23 if you want to merge it. I don't think it's too bloaty, adds 12 lines of template, ~6 lines of generated markup, 0 if you don't add the config params :)
