### ISSUE TITLE
Missing favicons

### ISSUE THREAD

**Issue by midzer** [ribice/kiss#24]
Hi,
great theme first of all! According to `theme.toml` this theme features favicons. But it's not implemented yet I think.

How about adding them in `header` partial directly? I suggest providing several favicons to support all browsers. Something like https://github.com/midzer/eisolzried/blob/master/_includes/meta.html for example. Will do a PR if you like.

Cheers midzer

**Comment by ribice** [comment]
You can create a PR. Thanks!

**Comment by russparsloe** [comment]
I've heard good things about https://realfavicongenerator.net/. If the updates to the partial could align to the output from there, I think it would put things in good shape.
