### ISSUE TITLE
Add option to hide pages from list view

### ISSUE THREAD

**Issue by russparsloe** [ribice/kiss#27]
With the recent addition of sections (#23) it would be good to have the option to hide pages from the list view (such as About page etc) using something in the frontmatter such as `hidden: true`.

If this if deemed to be a good idea, I'm happy to create a pull request.

**Comment by ribice** [comment]
@russparsloe Please do.

**Comment by ketkar** [comment]
@russparsloe This is a great idea! Are you still planning on implementing? Otherwise I'll give it a shot!
