### ISSUE TITLE
Add mastodon social network icon

### ISSUE THREAD

**Issue by kr428** [ribice/kiss#40]
Hi there; love that theme all along with hugo; only thing I possibly could wish for: Would it be possible to, all along with instagram and twitter, add an icon for the mastodon social network (https://joinmastodon.org/) to the upper right icon bar and configuration?

Thanks a bunch and all the best,
Kristian

**Comment by ribice** [comment]
FeatherIcons doesn't have a Mastodon icon ([perhaps request it there](https://github.com/feathericons/feather))?

Alternatively you can find an .svg of their logo and do it yourself (`data/theme.toml` and `layouts/partials/svg/icons.html`)

**Comment by kr428** [comment]
Ok, I'll look into that myself then. Thanks! :)
