### ISSUE TITLE
error when compiling, index.html

### ISSUE THREAD

**Issue by ppochon** [ribice/kiss#41]
Hello, I've got an error when compiling with `hugo server`:

`Building sites … ERROR 2018/06/24 13:25:27 Error while rendering "taxonomy" in "": html/template:theme/_default/list.html:1:12: no such template "index.html"
`
But it works with an older index.html

I'm runnig Hugo v.0.41

**Comment by ribice** [comment]
It's probably related to #39 

Will look into it later today.

**Comment by ribice** [comment]
Just checked, had the same error until I updated to latest version. With it, the error is gone.
