### ISSUE TITLE
Design fails when custom background is non-white

### ISSUE THREAD

**Issue by madeso** [ribice/kiss#42]
After the footer is complete, the background is set to transparent and in firefox it is picking up the standard browser background color. If this is set to anything other than #fff the design fails, in my case I have set it to solorized light.

The inspector points to style.css line 5549. Changing this to #fff instead of transparent fixes the issue.

**Comment by ribice** [comment]
Can you make a PR that fixes this? Thanks!

**Comment by madeso** [comment]
Sorry. Totally missed your comment somehow :(
