### ISSUE TITLE
Syntax highlighting not working

### ISSUE THREAD

**Issue by rchoudhary** [ribice/kiss#47]
I wanted to add syntax highlighting to my pages.

In `config.toml` I have these lines:

```
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "monokai"
```

Then in one of my post's markdown files I'll have snippets like this:

```
{{< highlight cpp "linenos=table" >}}
#include <iostream>
using namespace std;

int main() {
    cout << "hello world!" << endl;
}
{{< /highlight >}}
```

I then run `hugo server -D` to see my post at `http://localhost:1313/posts/<my-post>`.

The code block just ends up looking like this:

<img width="818" alt="screen shot 2018-09-04 at 2 39 18 am" src="https://user-images.githubusercontent.com/4595638/45016911-c27dcd80-afeb-11e8-933a-2d93fb02d09e.png">

**Comment by ribice** [comment]
I have only this in my config file: `pygmentsUseClasses = true`

Did you generate your syntax.css file?

Refer to this [LINK](https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css).
