### ISSUE TITLE
croma syntax highlighting changes fontsize

### ISSUE THREAD

**Issue by deisi** [ribice/kiss#61]
![fontsize](https://user-images.githubusercontent.com/5436980/50952390-9ea62900-14b0-11e9-9d81-243232196efb.png)

Any idea what is going on here? In my `config.toml` I have 

```
pygmentsUseClasses = true
pygmentsCodeFences = true
```

I generated style.css with:
```
hugo gen chromastyles --style=monokailight > syntax.css
```

And created a code block. If I enable any kind of syntax highlighting for the code block, it changes font size to an unpleasant small font. The raw code block without syntax highlighting has the same font size as the text though.

**Comment by ribice** [comment]
Should be resolved by #80
