### ISSUE TITLE
Using pygments syntax highlight themes are not honoured

### ISSUE THREAD

**Issue by p-prakash** [ribice/kiss#66]
I'm trying to use monokai theme for syntax highlighting but the dark theme is coming as background but kiss theme's style sheet overrides the background over the code text as show below.

**config.toml settings:**
```
theme = "kiss"
pygmentsCodefences = true
pygmentsUseClasses = false
pygmentsStyle = "monokai"
```

Screenshot:
<img width="801" alt="screenshot" src="https://user-images.githubusercontent.com/1238161/53300382-9a5a8300-3846-11e9-882f-1d5ca8f8ef83.png">

**Comment by ribice** [comment]
Resolved by #79
