### ISSUE TITLE
highlight.js support?

### ISSUE THREAD

**Issue by JosephDomenici** [ribice/kiss#7]
I really like this theme, but the lack of code highlighting is preventing me from switching over.

**Comment by ribice** [comment]
Why don't you use the chroma highlighter provided by hugo?

I'm using it just fine on my blog ([example link](https://www.ribice.ba/swagger-golang/)).

You can see the documentation [HERE](https://gohugo.io/content-management/syntax-highlighting/).

**Comment by JosephDomenici** [comment]
Apologies, I didn't realize Chroma was introduced back in September. Thanks!
