### ISSUE TITLE
Help adding canonical URL.

### ISSUE THREAD

**Issue by xyznaveen** [ribice/kiss#71]
How do I add `canonical URL` to this theme ?

**Comment by mogimogitomato** [comment]
@xyznaveen You could add `canonical URL` in the folowing steps.

1. Move hugo project's root directory.
1. Copy `themes/kiss/layouts/partials/header.html` to `layouts/partials` directory .
1. Add line of code `<link rel="canonical" href="{{ .Permalink }}">`  into `head` tag.

( reference: https://bwaycer.github.io/hugo_tutorial.hugo/themes/customizing )

**Comment by ribice** [comment]
@mogimogitomato Would this be a good change for PR? Not too much into SEO.

**Comment by mogimogitomato** [comment]
@ribice 
Exactly. I sent a pull request.
https://github.com/ribice/kiss/pull/73
