### ISSUE TITLE
function "site" not defined

### ISSUE THREAD

**Issue by bughou** [ribice/kiss#74]
hello, i got this error with the latest version of hugo and kiss:

ERROR 2019/09/06 19:43:19 Failed to add template "index.html" in path "index.html": template: index.html:5: function "site" not defined
ERROR 2019/09/06 19:43:19 index.html : template: index.html:5: function "site" not defined
Building sites … ERROR 2019/09/06 19:43:19 Error while rendering "home" in "": template: "index.html" is an incomplete or empty template
ERROR 2019/09/06 19:43:19 Error while rendering "section" in "": html/template:_default/list.html:1:12: "index.html" is an incomplete or empty template
ERROR 2019/09/06 19:43:19 Error while rendering "taxonomyTerm" in "": html/template:_default/list.html:1:12: "index.html" is an incomplete or empty template
Total in 27 ms
Error: Error building site: logged 5 error(s)

after rename "site" to ".Site" in layouts/index.html, it works.

**Comment by ribice** [comment]
What exactly do you rename? Can you submit a PR?

**Comment by ribice** [comment]
Have you tested after https://github.com/ribice/kiss/commit/302297164b08e65b18344ec7bb81901ad9dce95a ?

Are you still getting the same error?
