### ISSUE TITLE
After nav's page transition, page view is not change

### ISSUE THREAD

**Issue by mogimogitomato** [ribice/kiss#83]
- Environment
  - Hugo version: 0.59.1
  - kiss commit id: 073016f99669893a4dcea16b41ee5deea327445b

When I press nav's link, page view isn't change after nav's page transition.
In [Hugo's reference](https://gohugo.io/variables/site/#site-pages)(maybe since [v0.57.2](https://github.com/gohugoio/hugo/releases/tag/v0.57.2)..?),
`.Site.RegularPages` return *Collection of only regular pages*, and
`.RegularPages` return *Collection of only regular pages under the current list page* .

In kiss, layouts/_default/list.html called index.html, and in index.html `.Site.RegularPages`
only used. So I fix RegularPages's context, and sent PR.
Best Regards.

- Reproduction Gif
<img src="https://imgur.com/eCdiDQO.gif"/>

**Comment by ribice** [comment]
Should be resolved with #84
