### ISSUE TITLE
Summary of post

### ISSUE THREAD

**Issue by bmy4415** [ribice/kiss#88]
Hi, I'm new to hugo - kiss theme.

I'm writing my blog with kiss theme.
At homepage, I can see summary of each of my post.
But some text block enclosed with ` ``` `, which represents code block, exists in my summary therefore makes summary dirty. For example, see post `Hugo Tips`.

<img width="1280" alt="스크린샷 2020-01-18 오후 12 38 32" src="https://user-images.githubusercontent.com/29326383/72658099-a667aa00-39ef-11ea-9d45-b02f708e2452.png">

<img width="1280" alt="스크린샷 2020-01-18 오후 12 41 10" src="https://user-images.githubusercontent.com/29326383/72658113-d44cee80-39ef-11ea-83c6-e369d1a6b741.png">

I was adding ` ``` ` block but it's content (which is dirty command line results) appears directly in summary of post.

Is there any way to avoid this?

Thanks,
Jaewan

**Comment by ribice** [comment]
You can add the `<!--more-->` tag to define what will be shown in Summary.

**Comment by bmy4415** [comment]
Thanks! I can add this tag to my own markdown file.

**Comment by AdamSLevy** [comment]
@ribice Could you please clarify where `<!--more-->` should go to limit the summary of a post?

**Comment by btimofeev** [comment]
https://gohugo.io/content-management/summaries/
