### ISSUE TITLE
Render of taxonomyTerm failed

### ISSUE THREAD

**Issue by burrscurr** [ribice/kiss#89]
I am starting to use hugo + kiss and experienced an issue with the newest version of kiss on master. When using the v2.0.0 version, everything is fine.

When running `hugo server`, I get this error:
`
port 1313 already in use, attempting to use an available port
Total in 7 ms
Error: Error building site: failed to render pages: render of "taxonomyTerm" failed: execute of template failed: template: index.html:7:23: executing "index.html" at <$pctx.RegularPages>: can't evaluate field RegularPages in type *hugolib.pageState
`

Exact steps to reproduce:
- Create new hugo site with `hugo new site mysite`
- Clone kiss into themes (`git clone https://github.com/ribice/kiss.git`)
- Copy the exampleSite config.toml file to `mysite/config.toml`
- Running `hugo server` fails.

Hope it is an actual problem and not just caused by some type of wrong use :smile:

**Comment by ribice** [comment]
1. You have Hugo running twice I assume:

`port 1313 already in use`

2. What version of Hugo are you using? What commit of kiss is in `/themes/kiss`?

**Comment by burrscurr** [comment]
Yeah, hugo was running twice when I reproduced the error with a small example. I used the commit [554301b31fb55428fd3966564cd239f942e6c92f](https://github.com/ribice/kiss/tree/554301b31fb55428fd3966564cd239f942e6c92f).
`hugo version` says `ugo Static Site Generator v0.56.1/extended linux/amd64 BuildDate: unknown`.

**Comment by mogimogitomato** [comment]
@burrscurr 
In Hugo v0.57.2, there are include breaking changes.
https://github.com/gohugoio/hugo/releases/tag/v0.57.2
I fixed relevant location to follow the changes.
https://github.com/ribice/kiss/issues/83

So, please update your Hugo's version to 0.57.2 or higher.
