### ISSUE TITLE
Warning about date and/or time missing from archetype file

### ISSUE THREAD

**Issue by ploggingdev** [ribice/kiss#9]
When I create a new post using `hugo new post/post_name.md` , I get the following warning:

```
WARNING: date and/or title missing from archetype file "/home/frosty/Desktop/plogs/themes/kiss/archetypes/default.md".
From Hugo 0.24 this must be provided in the archetype file itself, if needed. Example:
---
title: "{{ replace .TranslationBaseName "-" " " | title }}"
date: {{ .Date }}
draft: true
---



/home/frosty/Desktop/plogs/content/post/building-hackers-chat.md created
```

**Comment by ribice** [comment]
Cloned the repo, ran the following command with hugo 0.33:

```bash
➜  demo-hugo hugo new post/post_name.md
/Users/ribice/code/web/demo-hugo/content/post/post_name.md created
```

Can you share your repo so I can test it myself? Which version of hugo are you using?

**Comment by ploggingdev** [comment]
I am using Hugo 0.33 and the same warning shows up even when I use the `exampleSite` code provided in the theme.

Since Hugo 0.24 the archetype file should contain the date and title,. Link to announcement [here](https://gohugo.io/news/0-24/).

I tried updating the archetype file here : https://github.com/ploggingdev/kiss/commit/1fc04927a1d5fcfda43e5c2d63328ff4a4c8d2e5 and the warning is no longer displayed.

Should I create a pull request?

**Comment by ribice** [comment]
Sure, go ahead.
