### ISSUE TITLE
Netlify deploy failed: can't evaluate field RegularPages

### ISSUE THREAD

**Issue by ElectionPlots** [ribice/kiss#92]
I tried to deploy a site using Kiss on Netify but the deploy failed with the following message: failed: execute of template failed: template: index.html:7:23: executing "index.html" at <$pctx.RegularPages>: can't evaluate field RegularPages in type *hugolib.PageOutput
I have used your original index.html without change.
Netlify deploy log attached.
[deploylog.txt](https://github.com/ribice/kiss/files/4172939/deploylog.txt)

**Comment by ribice** [comment]
What version of Hugo are you using?

**Comment by ElectionPlots** [comment]
The latest  0.64.0.

**Comment by ElectionPlots** [comment]
Now working with latest version. Not sure why it failed first time around.
