### ISSUE TITLE
Custom Social Media Icon not working

### ISSUE THREAD

**Issue by Suesswarendieb** [ribice/kiss#94]
Hi there,

I tried to add my own custom social media icon to the navbar. The SVG part works like a charm, but the resulting href is incorrect.

To data/theme.toml I added 
`xmpp =  'xmpp:'`

In my site's config, I set the corresponding links and order:
```
[params.social]
email = "email@gmail.com"
xmpp = "jid@xmppserver.com"

[params.social.config]
platforms = ["email","xmpp"]
```

So in theory the corresponding href should be xmpp:jid@xmppserver.com. But instead the generated HTML is something like:
`<a class="level-item" aria-label="xmpp" href='#ZgotmplZ' target='_blank' rel='noopener'> svg stuff </a>`

**Comment by olehermanse** [comment]
@Suesswarendieb could you share all the changes you made, since you said the svg part worked like a charm?

You should be able to do something similar to this:

https://github.com/ribice/kiss/pull/93/files

**Comment by Suesswarendieb** [comment]
Yeah I did orientate on these changes.

data/theme.toml 
```
[social.base]
codepen = 'https://codepen.io/'
email =  'mailto:'
xmpp =  'xmpp:'
facebook = 'https://facebook.com/'
github = 'https://github.com/'
instagram = 'https://instagram.com/'
linkedin = 'https://linkedin.com/in/'
twitter = 'https://twitter.com/'
youtube = 'https://youtube.com/user/'
gitlab = 'https://gitlab.com/'
rss = '/'
about = '/'
```
Note that in the xmpp line, I put two spaces after the equals sign, just like it's done in the email line. (Is this on purpose? Does this do anything?)

To layouts/partials/svg/icons.html I added:
```
    {{ else if eq "xmpp" . }}
    <path d="M 2 4 C 2 12.533 12 20 17 20 L 17 18.933594 C 8 17.866594 8 6.1328125 8 6.1328125 L 2 4 z M 22 4 L 16 6.1308594 C 16 6.1308594 15.999219 12.139219 12.699219 15.949219 C 13.139219 16.359219 13.629687 16.719531 14.179688 17.019531 C 18.239688 14.069531 22 9.23 22 4 z M 9.7207031 18.189453 C 8.9207031 18.549453 8.02 18.809687 7 18.929688 L 7 20 C 8.12 20 9.4796875 19.629219 10.929688 18.949219 C 10.519688 18.709219 10.120703 18.459453 9.7207031 18.189453 z"/>
```
And finally the corresponding parts in my config.toml
```
[params.social]
email = "email@gmail.com"
xmpp = "jid@xmppserver.com"

[params.social.config]
platforms = ["email","xmpp"]
```

**Comment by mogimogitomato** [comment]
@Suesswarendieb 

In [gohugo.io](https://gohugo.io/functions/safeurl/), 

```
Without safeURL, only the URI schemes http:, https: and mailto: are 
considered safe by Go templates. 
If any other URI schemes (e.g., irc: and javascript:) are detected, 
the whole URL will be replaced with #ZgotmplZ. 
This is to “defang” any potential attack in the URL by rendering it useless.
```

So, you may be need to add `safeURL` in themes/kiss/layouts/partials/nav.html 
`<a class="level-item" aria-label="{{ $platform }}" href='{{ print ( index $.Site.Data.theme.social.base $platform ) $username | safeURL }}'`

**Comment by Suesswarendieb** [comment]
> So, you may be need to add safeURL in themes/kiss/layouts/partials/nav.html
`<a class="level-item" aria-label="{{ $platform }}" href='{{ print ( index $.Site.Data.theme.social.base $platform ) $username | safeURL }}'`

Yes! This got it working. Thanks a lot :)
